project:
  type: website
  output-dir: ../docs

website:
  title: "The ECON Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: Team
      - href: projects.qmd
        text: Research
